<a href="https://colab.research.google.com/github/ldl23333/MAT494/blob/main/Homework_3_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework 3.7

1. Load and prepare the MNIST dataset

In [1]:
import tensorflow as tf

In [2]:
# load the dataset
mnist = tf.keras.datasets.mnist

# convert the samples from integers to floating-point numbers
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


2. Build the tf.keras.Sequential model by stacking layers.

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.3578151 , -0.18092543,  0.10100691, -0.6844629 , -0.26471305,
         0.3390288 , -0.13943173,  0.83390915, -0.6437076 , -0.2903165 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.07163315, 0.08549412, 0.11333863, 0.0516717 , 0.07862267,
        0.1437969 , 0.08911622, 0.23587035, 0.05382109, 0.07663521]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2932 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1419 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1071 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0882 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0739 - accuracy: 0.9768


3. Evaluate the Model

In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0782 - accuracy: 0.9763 - 797ms/epoch - 3ms/step


[0.07816009223461151, 0.9763000011444092]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.4408623e-07, 5.3013429e-09, 4.1989024e-05, 1.3771269e-04,
        4.0509790e-10, 8.3432622e-07, 3.7070444e-13, 9.9971372e-01,
        1.8437706e-07, 1.0504001e-04],
       [3.3712733e-13, 3.7294533e-04, 9.9962568e-01, 1.1377659e-06,
        1.9478341e-13, 1.3655099e-07, 2.5428655e-08, 1.6412680e-12,
        1.3287107e-07, 7.9573327e-12],
       [1.3157536e-07, 9.9940991e-01, 2.2145847e-04, 1.5459016e-05,
        2.8652801e-05, 2.9328885e-06, 2.7025078e-05, 1.8974692e-04,
        1.0410529e-04, 6.7631316e-07],
       [9.9865192e-01, 4.4040376e-09, 1.0792401e-03, 1.1653018e-06,
        3.3793058e-05, 3.0611725e-05, 6.5139189e-05, 6.6765053e-05,
        1.0260154e-06, 7.0337075e-05],
       [3.8483611e-07, 5.0645532e-10, 2.8316713e-06, 2.0335273e-09,
        9.9966288e-01, 1.5131808e-07, 1.1750900e-06, 1.5417445e-05,
        8.5009537e-09, 3.1712971e-04]], dtype=float32)>

In [12]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.