<a href="https://colab.research.google.com/github/ldl23333/MAT494/blob/main/Homework1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MAT 494 HW 1.2

In [17]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a = np.zeros((3, 5))
# note the extra bracket you need for calling np.zeros
print(a, '\n')

# shape of the array
print('len =',len(a))
print('shape =',a.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

len = 3
shape = (3, 5)


In [19]:
# pick two output valuables from a method
a = np.zeros((3,5))
nx,ny = a.shape
print('nx =', nx)
print('ny =', ny)

nx = 3
ny = 5


In [20]:
# ways to generate a constant array

a = np.zeros((3,5)) + 7
print(a, '\n')

b = np.ones((3,5)) * 7
print(b, '\n')

c = np.full((3,5), 7)
print(c)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [21]:
# identity matrix function eye()
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
# index
a = np.array(([1,2], [3,4], [5,6]))
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
# slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [24]:
# mix integer and slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[1, :]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]


In [25]:
# use two list as index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')
print(a[[0,1,2],[2,1,2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 3  6 11]


In [26]:
# update values
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[1,:] += 10
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [ 0.  1.  2.]]


In [27]:
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[:,2] = 5.
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[0. 1. 5.]
 [0. 1. 5.]
 [0. 1. 5.]]


In [28]:
# type of data in the array
a=np.array(([1,1],[1,1]))
print(a)
print(a.dtype)


[[1 1]
 [1 1]]
int64


In [29]:
a=np.array(([1.,1],[1,1]))
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64


In [30]:
a=np.array(([1.,1],[1,1]))>2
print(a)
print(a.dtype)

[[False False]
 [False False]]
bool


In [31]:
a=np.array((['1','1'],['1','1']))
print(a)
print(a.dtype)

[['1' '1']
 ['1' '1']]
<U1


In [32]:
a=np.array((['1','1'],['1','1']),dtype=float)
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64
